// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ChekRegestrationTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void chekRegestration() {
    driver.get("https://javaguru.lv/");
    driver.manage().window().setSize(new Dimension(945, 1020));
    driver.findElement(By.linkText("LV")).click();
    driver.findElement(By.cssSelector(".line:nth-child(2)")).click();
    driver.findElement(By.linkText("Kursi")).click();
    driver.findElement(By.cssSelector(".single-course:nth-child(3) .default-button")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".footer-element:nth-child(2) a"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.name("form-name")).click();
    driver.findElement(By.name("form-name")).sendKeys("sds");
    driver.findElement(By.name("form-phone")).click();
    driver.findElement(By.name("form-phone")).sendKeys("sffsf");
    driver.findElement(By.name("form-email")).click();
    driver.findElement(By.name("form-email")).sendKeys("fsfss");
    driver.findElement(By.cssSelector(".label")).click();
    driver.findElement(By.cssSelector(".last")).click();
    driver.findElement(By.cssSelector(".checkbox-mark")).click();
    driver.findElement(By.cssSelector(".default-button-submit")).click();
    driver.findElement(By.cssSelector(".footer")).click();
    driver.close();
  }
}
