// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class JAVAGURUTESTTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void jAVAGURUTEST() {
    driver.get("https://javaguru.lv/");
    driver.manage().window().setSize(new Dimension(1550, 830));
    driver.findElement(By.cssSelector(".single-hero-button > .pulse-button")).click();
    driver.findElement(By.name("form-name")).click();
    driver.findElement(By.name("form-name")).sendKeys("JHVUYUYFUYFUYG");
    driver.findElement(By.name("form-surname")).click();
    driver.findElement(By.name("form-surname")).sendKeys("OIHOIHOHOIH");
    driver.findElement(By.name("form-email")).click();
    driver.findElement(By.name("form-email")).sendKeys("JKBHHBJBJB");
    driver.findElement(By.name("form-phone")).click();
    driver.findElement(By.name("form-phone")).sendKeys("2345678900");
    driver.findElement(By.cssSelector(".selectric-course-input > .selectric")).click();
    driver.findElement(By.cssSelector(".selectric-scroll li:nth-child(5)")).click();
    js.executeScript("window.scrollTo(0,316.79998779296875)");
    driver.findElement(By.name("form-message")).click();
    driver.findElement(By.name("form-message")).sendKeys("ofwihoeiwhfoiewhfoiweopoewfjop");
    driver.findElement(By.cssSelector(".privacy-input > .checkbox-mark")).click();
    driver.findElement(By.cssSelector(".checkbox-single:nth-child(2) .checkbox-mark")).click();
    driver.findElement(By.cssSelector(".submit-button > .default-button")).click();
  }
}
