// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class JavaGuruTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void javaGuruTest() {
    driver.get("https://www.google.com/");
    driver.manage().window().setSize(new Dimension(1464, 816));
    driver.findElement(By.name("q")).sendKeys("JavaGuru");
    driver.findElement(By.cssSelector(".sbre .wM6W7d > span")).click();
    js.executeScript("window.scrollTo(0,24.799999237060547)");
    driver.findElement(By.cssSelector(".tF2Cxc > .yuRUbf .LC20lb")).click();
    driver.findElement(By.linkText("LV")).click();
    driver.findElement(By.cssSelector(".menu li:nth-child(1) > a")).click();
    js.executeScript("window.scrollTo(0,400)");
    js.executeScript("window.scrollTo(0,768.7999877929688)");
    js.executeScript("window.scrollTo(0,4133.60009765625)");
    js.executeScript("window.scrollTo(0,5140)");
  }
}
