// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class JGRegistrationTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void jGRegistration() {
    // Test name: JG_Registration
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.google.lv//");
    // 2 | setWindowSize | 1520x808 | 
    driver.manage().window().setSize(new Dimension(1520, 808));
    // 3 | click | css=.header-button > .default-button | 
    driver.findElement(By.cssSelector(".header-button > .default-button")).click();
    // 4 | click | name=form-name | 
    driver.findElement(By.name("form-name")).click();
    // 5 | type | name=form-name | fgmnjxgh
    driver.findElement(By.name("form-name")).sendKeys("fgmnjxgh");
    // 6 | click | name=form-surname | 
    driver.findElement(By.name("form-surname")).click();
    // 7 | type | name=form-surname | xgfjnf
    driver.findElement(By.name("form-surname")).sendKeys("xgfjnf");
    // 8 | click | name=form-email | 
    driver.findElement(By.name("form-email")).click();
    // 9 | type | name=form-email | xgfjh
    driver.findElement(By.name("form-email")).sendKeys("xgfjh");
    // 10 | click | name=form-phone | 
    driver.findElement(By.name("form-phone")).click();
    // 11 | type | name=form-phone | xgfjh
    driver.findElement(By.name("form-phone")).sendKeys("xgfjh");
    // 12 | click | css=.selectric-course-input > .selectric | 
    driver.findElement(By.cssSelector(".selectric-course-input > .selectric")).click();
    // 13 | click | css=.selectric-scroll li:nth-child(6) | 
    driver.findElement(By.cssSelector(".selectric-scroll li:nth-child(6)")).click();
    // 14 | click | name=form-message | 
    driver.findElement(By.name("form-message")).click();
    // 15 | type | name=form-message | gjfxj
    driver.findElement(By.name("form-message")).sendKeys("gjfxj");
    // 16 | click | css=.privacy-input img | 
    driver.findElement(By.cssSelector(".privacy-input img")).click();
    // 17 | click | css=.submit-button > .default-button | 
    driver.findElement(By.cssSelector(".submit-button > .default-button")).click();
    // 18 | click | css=.logo img | 
    driver.findElement(By.cssSelector(".logo img")).click();
    // 19 | click | css=.menu li:nth-child(1) > a | 
    driver.findElement(By.cssSelector(".menu li:nth-child(1) > a")).click();
    // 20 | click | css=.menu li:nth-child(7) > a | 
    driver.findElement(By.cssSelector(".menu li:nth-child(7) > a")).click();
    // 21 | click | name=form-name | 
    driver.findElement(By.name("form-name")).click();
    // 22 | type | name=form-name | xjfgjf
    driver.findElement(By.name("form-name")).sendKeys("xjfgjf");
    // 23 | click | name=form-surname | 
    driver.findElement(By.name("form-surname")).click();
    // 24 | type | name=form-surname | fxgj
    driver.findElement(By.name("form-surname")).sendKeys("fxgj");
    // 25 | click | name=form-phone | 
    driver.findElement(By.name("form-phone")).click();
    // 26 | type | name=form-phone | xfgj
    driver.findElement(By.name("form-phone")).sendKeys("xfgj");
    // 27 | click | name=form-email | 
    driver.findElement(By.name("form-email")).click();
    // 28 | type | name=form-email | xfgj
    driver.findElement(By.name("form-email")).sendKeys("xfgj");
    // 29 | click | name=form-message | 
    driver.findElement(By.name("form-message")).click();
    // 30 | type | name=form-message | xgj
    driver.findElement(By.name("form-message")).sendKeys("xgj");
    // 31 | click | css=.checkbox-mark > img | 
    driver.findElement(By.cssSelector(".checkbox-mark > img")).click();
    // 32 | click | css=.submit-button > .default-button | 
    driver.findElement(By.cssSelector(".submit-button > .default-button")).click();
    // 33 | click | css=.logo img | 
    driver.findElement(By.cssSelector(".logo img")).click();
  }
}
