// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class GooglejavagurutestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void googlejavagurutest() {
    driver.get("https://www.google.com/");
    driver.manage().window().setSize(new Dimension(1266, 965));
    driver.findElement(By.name("q")).sendKeys("java");
    driver.findElement(By.cssSelector("#jZ2SBf > .wM6W7d > span")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("div:nth-child(2) > .tF2Cxc .LC20lb"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("div:nth-child(2) > .tF2Cxc .LC20lb")).click();
    driver.findElement(By.cssSelector(".menu li:nth-child(1) > a")).click();
    driver.findElement(By.cssSelector(".single-list:nth-child(2) .single-course:nth-child(2) .default-button")).click();
    driver.findElement(By.name("form-name")).click();
    driver.findElement(By.name("form-name")).sendKeys("cccc");
    driver.findElement(By.cssSelector(".phone-input-wrapper")).click();
    driver.findElement(By.name("form-phone")).click();
    driver.findElement(By.name("form-phone")).sendKeys("cc");
    driver.findElement(By.name("form-email")).click();
    driver.findElement(By.name("form-email")).sendKeys("cc");
    driver.findElement(By.cssSelector(".selectric:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".label")).click();
    driver.findElement(By.cssSelector(".selectric:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".default-button-submit")).click();
  }
}
